<?php
function icon(string $name,string $class=''):string{
 $paths=[ 'menu'=>'<path d="M4 6h16M4 12h16M4 18h16"/>','home'=>'<path d="m3 10 9-7 9 7v10a1 1 0 0 1-1 1h-5v-7H9v7H4a1 1 0 0 1-1-1z"/>','book'=>'<path d="M12 5v16M3 3c4-1 7 0 9 2 2-2 5-3 9-2v16c-4-1-7 0-9 2-2-2-5-3-9-2z"/>','star'=>'<path d="m12 3 2.8 5.7 6.2.9-4.5 4.4 1.1 6.2L12 17.3l-5.6 2.9 1.1-6.2L3 9.6l6.2-.9z"/>','bolt'=>'<path d="m13 2-9 12h7l-1 8 10-13h-8z"/>','check'=>'<path d="m5 12 4 4L19 6"/>','lock'=>'<rect x="5" y="10" width="14" height="11" rx="3"/><path d="M8 10V7a4 4 0 0 1 8 0v3m-4 5v2"/>','arrow'=>'<path d="M4 12h16m-6-6 6 6-6 6"/>','close'=>'<path d="m6 6 12 12M6 18 18 6"/>','people'=>'<circle cx="9" cy="7" r="3"/><path d="M3 21v-3a6 6 0 0 1 12 0v3m1-17a3 3 0 0 1 0 6m3 11v-3a6 6 0 0 0-3-5"/>','user'=>'<circle cx="12" cy="7" r="4"/><path d="M4 21v-2a8 8 0 0 1 16 0v2"/>','sound'=>'<path d="m11 4-5 4H3v8h3l5 4zm4 4a6 6 0 0 1 0 8m3-11a10 10 0 0 1 0 14"/>','mic'=>'<rect x="9" y="2" width="6" height="13" rx="3"/><path d="M5 10v2a7 7 0 0 0 14 0v-2m-7 9v3m-4 0h8"/>','pause'=>'<path d="M8 5v14M16 5v14"/>','stop'=>'<rect x="5" y="5" width="14" height="14" rx="2"/>','replay'=>'<path d="M4 10a8 8 0 1 1 1 8M4 4v6h6"/>','mute'=>'<path d="m11 4-5 4H3v8h3l5 4zm5 5 6 6m0-6-6 6"/>','logout'=>'<path d="M9 3H4v18h5m0-9h13m-5-5 5 5-5 5"/>','settings'=>'<circle cx="12" cy="12" r="4"/><path d="M12 2v3m0 14v3M2 12h3m14 0h3M5 5l2 2m10 10 2 2M5 19l2-2M17 7l2-2"/>','image'=>'<rect x="3" y="3" width="18" height="18" rx="3"/><circle cx="8" cy="8" r="2"/><path d="m3 17 5-5 4 4 4-6 5 6"/>','clock'=>'<circle cx="12" cy="12" r="9"/><path d="M12 6v6l4 2"/>','flag'=>'<path d="M5 22V3c6-4 8 4 15 0v11c-7 4-9-4-15 0"/>','edit'=>'<path d="m3 17 13-13 4 4L7 21H3zm10-10 4 4"/>','fire'=>'<path d="M13 2c2 7-6 6-3 12 2-1 3-3 3-4 7 5 7 12-1 12S0 13 7 7c0 4 2 4 3 4-2-4 3-6 3-9z"/>' ];
 return '<svg class="icon '.e($class).'" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">'.($paths[$name]??$paths['book']).'</svg>';
}
function avatar(array $u):string{
 $path=(string)($u['avatar_path']??'');
 return $path&&local_image_file($path)?'<img class="avatar" src="'.e($path).'" alt="Profile photo of '.e($u['name']).'">':'<img class="avatar default-avatar" src="assets/design/default-avatar.svg" alt="Default profile picture for '.e($u['name']).'">';
}
function head(string $title,string $class=''):void{echo '<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="csrf" content="'.e(csrf()).'"><title>'.e($title).' · BULIG</title><link rel="icon" href="assets/favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="assets/style.css?v=4"><link rel="stylesheet" href="assets/design.css?v=8"><script defer src="assets/app.js?v=8"></script></head><body class="'.e($class).'">';}
function foot():void{echo '</body></html>';}
function notice():void{if(isset($_SESSION['flash'])){echo '<div class="notice" role="status">'.icon('check').'<span>'.e($_SESSION['flash']).'</span></div>';unset($_SESSION['flash']);}}
function shell(array $u,string $page):void{
 head(ucfirst(str_replace('_',' ',$page)),'workspace role-'.$u['role'].' view-'.preg_replace('/[^a-z_]/','',$page));$nav=$u['role']==='pupil'?['dashboard'=>['home','My learning'],'achievements'=>['star','My achievements'],'profile'=>['user','My profile']]:($u['role']==='teacher'?['dashboard'=>['home','Overview'],'class_demo'=>['book','Class Demo'],'accounts'=>['people','My pupils'],'sections'=>['people','My sections'],'review'=>['check','Activity history'],'guide'=>['book','Teaching guide'],'profile'=>['user','My profile']]:['dashboard'=>['home','Overview'],'accounts'=>['people','Teachers'],'content'=>['book','Lesson studio'],'media'=>['image','Official visuals'],'issues'=>['flag','Content notes'],'settings'=>['settings','Badges & rewards'],'profile'=>['user','My profile']]);
 echo '<button type="button" class="mobile-menu-toggle" aria-controls="mobile-sidebar" aria-expanded="false" aria-label="Open navigation">'.icon('menu').' Menu</button><div class="sidebar-shade" hidden></div><aside class="sidebar" id="mobile-sidebar" aria-label="Main navigation"><button type="button" class="sidebar-close" aria-label="Close navigation">'.icon('close').'</button><a class="brand" href="?page=dashboard"><img src="assets/bulig-logo.png" alt="BULIG"><span>Little steps. Brighter futures.</span></a><p class="navlabel">'.e($u['role']==='pupil'?'YOUR LEARNING SPACE':strtoupper($u['role']).' WORKSPACE').'</p><nav>';foreach($nav as $key=>$v)echo '<a class="navitem '.($page===$key?'selected':'').'" href="?page='.$key.'">'.icon($v[0]).e($v[1]).'</a>';
 echo '</nav><div class="sidebar-bottom"><div class="person">'.avatar($u).'<div><strong>'.e($u['name']).'</strong><small>'.e($u['public_id']).'</small></div></div><form method="post">'.csrf_field().'<input type="hidden" name="action" value="logout"><button class="signout">'.icon('logout').'Sign out</button></form></div></aside><div class="mainwrap"><a class="mobile-brand" href="?page=dashboard" aria-label="BULIG home"><img src="assets/bulig-logo.png" alt="BULIG"></a><header class="topbar"><span>BUKIDNON’S UNIFIED LITERACY AND INTERVENTION GATEWAY</span><span class="rolepill">'.e(ucfirst($u['role'])).'</span></header><main class="main">';notice();identity_banner($u,$page);
}
function shell_end():void{echo '</main><footer class="sitefooter">BULIG · Building Up Literacy, Inspiring Growth</footer></div>';foot();}
function source_link(int $n,int $lid=0):string{
 $level=$lid?lesson_level($lid):1;
 if(in_array($level,[2,3],true)){
  $meta=level2_manifest()['levels'][(string)$level];
  if((current_user()['role']??'')==='pupil'&&!in_array($n,$meta['pupil_pages'],true))return '';
 }
 return '<a class="source-link" href="?page=source&amp;level='.$level.'&amp;n='.$n.'" target="_blank" rel="noopener">'.icon('book').'Official '.e(level_label($level)).' · PDF page '.$n.'</a>';
}

function login_view():void{
 $role=in_array($_GET['role']??'',['pupil','teacher','admin'],true)?$_GET['role']:'pupil';head('Welcome','login-page');
 echo '<main class="login-layout"><section class="login-story"><a class="login-brand" href="?page=login"><img src="assets/bulig-logo.png" alt="BULIG"></a><div class="story-content"><span class="eyebrow">A LITTLE PRACTICE. A LOT OF POSSIBILITY.</span><h1>Small steps.<br>Bright futures.</h1><p>A welcoming place to read, speak, and grow.<br>Your next adventure starts with a little practice.</p><div class="story-photo"><img src="'.'assets/design/reading-garden.svg'.'" alt="An open book in a leafy learning garden"><span>'.icon('book').'Level 1 · Oral Language</span></div></div><small>Building Up Literacy, Inspiring Growth</small></section><section class="login-panel"><div class="login-card">';notice();
 echo '<span class="eyebrow">WELCOME TO BULIG</span><h2>'.($role==='pupil'?'Your next adventure<br>starts here.':($role==='teacher'?'Welcome back,<br>teacher.':'Administrator<br>sign in.')).'</h2><p class="muted">'.($role==='pupil'?'A little practice. A little discovery. A brighter day.':'Sign in to your BULIG workspace.').'</p><nav class="role-tabs"><a class="'.($role==='pupil'?'active':'').'" href="?page=login&role=pupil">'.icon('user').'Pupil</a><a class="'.($role==='teacher'?'active':'').'" href="?page=login&role=teacher">'.icon('people').'Teacher</a></nav><form method="post" class="stack">'.csrf_field().'<input type="hidden" name="action" value="login"><input type="hidden" name="role" value="'.$role.'"><label>'.ucfirst($role).' ID<input name="public_id" autocomplete="username" required maxlength="30" '.($role==='pupil'?'inputmode="numeric"':'').' placeholder="'.($role==='pupil'?'Enter your pupil ID':($role==='teacher'?'Enter your teacher ID':'Enter your admin ID')).'"></label><label>Password<span class="password-field"><input id="password" name="password" type="password" autocomplete="current-password" required maxlength="72" placeholder="Enter your password"><button type="button" class="show-password" data-password="password">Show</button></span></label><button class="btn primary full" type="submit">Let’s go '.icon('arrow').'</button></form><div class="login-help">'.icon('lock').'<span>'.($role==='pupil'?'Need help signing in? Ask your teacher.':'Need help signing in? Ask your administrator.').'</span></div><a class="admin-entry" href="?page=login&role=admin">Administrator access</a></div></section></main>';foot();
}
function pupil_dashboard(array $u):void{
 $pid=(int)$u['id'];$s=progress_stats($pid);$assign=one('SELECT l.* FROM bulig_levels l JOIN pupil_level_assignments a ON a.level_id=l.id WHERE a.pupil_id=?',[$pid]);pupil_progress_cards($pid,$s,$assign);
 $level=(int)($_GET['level']??0);
 if(!$level){pupil_next_step($pid);level_cards($assign);return;}
 if(!level_available($pid,$level))fail('This level is not available yet. Complete your earlier level or ask your teacher about your starting level.',403);
 $lessons=rows('SELECT l.*,p.completed_at FROM lessons l JOIN modules m ON m.id=l.module_id LEFT JOIN pupil_progress p ON p.lesson_id=l.id AND p.pupil_id=? WHERE m.level_id=? AND l.published=1 ORDER BY l.position',[$pid,$level]);
 $done=count(array_filter($lessons,fn($l)=>(bool)$l['completed_at']));$total=count($lessons);$current=null;foreach($lessons as $l)if(!$l['completed_at']){$current=$l;break;}
 echo '<a class="btn secondary" href="?page=dashboard">Back to all levels</a><section class="journey" id="level'.$level.'-path"><div class="level-banner"><div><span class="eyebrow">'.e(level_label($level)).'</span><h2>'.($level===1?'Find your voice.':'Discover the sounds in words.').'</h2><p>'.$total.' learning steps · '.$done.' complete</p></div><span class="banner-icon">'.icon('book').'</span></div><div class="journey-head"><strong>Your learning path</strong><span>'.round($done/max(1,$total)*100).'% complete</span></div><progress max="'.$total.'" value="'.$done.'" aria-label="Completed learning steps"></progress><div class="lesson-path">';
 foreach($lessons as $l){$available=lesson_available($pid,(int)$l['id']);$complete=(bool)$l['completed_at'];$active=$available&&!$complete;echo '<div class="path-row '.($complete?'done':($active?'current':'locked')).'"><div class="path-node">'.icon($complete?'check':($active?'book':'lock')).'</div><div class="path-copy"><span class="eyebrow">STEP '.(int)$l['position'].($active?' · YOU ARE HERE':'').'</span><h3>'.e($l['subtitle']).'</h3><p>'.e($l['title']).'</p></div>'.($available?'<a class="btn '.($active?'primary':'quiet').'" href="?page=lesson&id='.$l['id'].'">'.($complete?'Review':'Continue').icon('arrow').'</a>':'<span class="lockedlabel">Locked</span>').'</div>';}
 echo '</div></section>';if(!$current)echo '<section class="card"><h2>You completed '.e(level_label($level)).'!</h2><p>Explore your next available level, or revisit your saved work.</p><a class="btn primary" href="?page=dashboard">See my levels '.icon('arrow').'</a></section>';
}

function lesson_view(array $u):void{
 $pid=(int)$u['id'];$lid=(int)($_GET['id']??1);if(!lesson_available($pid,$lid))fail('This lesson is not available yet.',403);$lesson=one('SELECT * FROM lessons WHERE id=?',[$lid]);$all=activities($lid,$pid);$aid=(int)($_GET['activity']??0);$chosen=null;
 if($aid){allowed_activity($pid,$aid);foreach($all as $item)if((int)$item['id']===$aid)$chosen=$item;if(!$chosen)fail('Activity does not belong to this lesson.',404);}else $chosen=next_activity($pid,$lid);
 $done=count(array_filter($all,fn($a)=>completion_ok($a)));$finished=(bool)val('SELECT completed_at FROM pupil_progress WHERE pupil_id=? AND lesson_id=?',[$pid,$lid]);
 head(level_label(lesson_level($lid)).' · '.$lesson['subtitle'],'activity-page');echo '<header class="activity-header"><a class="iconbutton" href="?page=dashboard" aria-label="Back to my learning">'.icon('close').'</a><div><strong>'.e(level_label(lesson_level($lid)).' · '.$lesson['subtitle']).'</strong><span>'.e($lesson['title']).'</span></div><div class="activity-progress"><span>'.$done.' / '.count($all).' complete</span><progress max="'.count($all).'" value="'.$done.'"></progress></div></header><main class="activity-main">';notice();
 if(!$chosen){
  $xp=(int)val('SELECT COALESCE(SUM(x.amount),0) FROM xp_transactions x JOIN activities a ON a.id=x.activity_id WHERE x.pupil_id=? AND a.lesson_id=?',[$pid,$lid]);
  echo '<section class="completion-card"><span class="big-symbol">'.icon('star').'</span><span class="eyebrow">LESSON '.$lesson['position'].'</span><h1>'.($finished?'Lesson complete!':'You did it!').'</h1><p>You earned <strong>'.$xp.' XP</strong> and gave your voice a little more practice.</p>';
  if($finished)echo '<a class="btn primary" href="?page=dashboard">Back to my learning '.icon('arrow').'</a>';
  else echo '<form method="post">'.csrf_field().'<input type="hidden" name="action" value="finish_lesson"><input type="hidden" name="lesson_id" value="'.$lid.'"><button class="btn primary next">Done '.icon('check').'</button></form>';
  echo '</section>';
 }else{
  $a=$chosen;$mode=$a['response_mode'];$question=one('SELECT * FROM questions WHERE activity_id=?',[$a['id']]);$exact=$question&&$question['grading']==='exact';if($exact)$mode='answer';$readonly=completion_ok($a);
  $draft=one('SELECT * FROM activity_drafts WHERE pupil_id=? AND activity_id=?',[$pid,$a['id']]);$response=$draft['response']??$a['response']??'';$drawing=$draft['drawing']??$a['drawing']??'';$transcript=$draft['transcript']??'';$imgs=activity_images($a);$worksheet=in_array(lesson_level($lid),[2,3],true)&&$mode==='drawing'&&count($imgs)===1;
  echo '<div class="activity-meta"><span class="eyebrow">LESSON '.$lesson['position'].' · '.e(['pre'=>'BEFORE WE BEGIN','learn'=>'LET’S PRACTICE','post'=>'SHOW WHAT YOU LEARNED'][$a['phase']]).'</span><span class="xpchip">'.icon('bolt').(int)$a['xp_reward'].' XP</span></div>';
  narration_controls($a['narration']);echo '<h1 class="activity-title">'.e($a['title']).'</h1><p class="activity-instruction">'.e($a['instructions']).'</p>';
  if(!$worksheet)render_activity_visuals($a);

  if($a['feedback'])echo '<div class="feedback"><div><strong>A note from your teacher</strong><p>'.e($a['feedback']).'</p></div></div>';
  echo '<form method="post" id="activity-form" class="activity-form" data-mode="'.e($mode).'" data-draft="'.($readonly?'off':'on').'">'.csrf_field().'<input type="hidden" name="action" value="submit"><input type="hidden" name="activity_id" value="'.$a['id'].'"><input type="hidden" name="transcript" id="transcript" value="'.e($transcript).'"><input type="hidden" name="drawing" id="drawing-data" value="'.e($drawing).'"><input type="hidden" id="expected-text" value="'.e($a['expected_text']??'').'">';
  if($mode==='answer'&&$a['type']==='sentence')echo '<div class="answer-card sentence-card"><label for="response">'.e($a['prompt']).'</label><input id="response" name="response" value="'.e($response).'" maxlength="12000" placeholder="Your answer" autocomplete="off" '.($readonly?'readonly':'required').'></div>';
  else{
   echo '<div class="answer-card"><div class="prompt '.(strlen($a['prompt'])>800?'longprompt':'').'">'.nl2br(e($a['prompt'])).'</div>';
   if(in_array($mode,['answer','drawing'],true)){
    if($a['type']==='choice')foreach(rows('SELECT an.content FROM answers an JOIN questions q ON q.id=an.question_id WHERE q.activity_id=?',[$a['id']]) as $op)echo '<label class="answer-option"><input type="radio" name="response" value="'.e($op['content']).'" '.($response===$op['content']?'checked':'').' '.($readonly?'disabled':'required').'>'.e($op['content']).'</label>';
    else echo '<label class="response-label" for="response">'.($worksheet?'Your numbered answers (or mark the sheet below)':($mode==='drawing'?'Tell us about your drawing (optional)':'Your answer')).'</label><textarea id="response" name="response" rows="3" maxlength="12000" placeholder="Type here, or tap Speak Answer…" '.($readonly?'readonly':($mode==='answer'?'required':'')).'>'.e($response).'</textarea>';
   }echo '</div>';
  }
  if($mode==='drawing'){
   $bg=$worksheet?resolved_image_path($imgs[0]):null;$size=$bg?getimagesize(__DIR__.'/../public/'.$bg):[900,500];
   echo '<div class="drawing-panel '.($worksheet?'worksheet-panel pan-mode':'').'"><div class="drawing-toolbar"><strong>'.($worksheet?'Your activity sheet':'Your drawing').'</strong><label>Color <input type="color" id="pen-color" value="#217c4b"></label><button class="btn quiet" type="button" id="clear-drawing">Clear my marks</button>'.($worksheet?'<button class="btn secondary" type="button" id="worksheet-pen" aria-pressed="false">Use pen</button><button class="btn secondary" type="button" id="worksheet-zoom" aria-pressed="false">Enlarge sheet</button><a href="'.e($bg).'" target="_blank" rel="noopener">Open original</a>':'').'</div><div class="worksheet-scroll"><div class="worksheet-surface">'.($bg?'<img class="worksheet-background" src="'.e($bg).'" alt="Original worksheet. Use numbered text answers above or draw on this sheet.">':'').'<canvas id="drawing-canvas" width="'.$size[0].'" height="'.$size[1].'" aria-label="Drawing area; you may also answer in text"></canvas></div></div><small>Choose Use pen to draw; choose Move sheet to scroll. Enlarge sheet helps with small print. You can type or speak numbered answers instead.</small></div>';
  }
  if(!$readonly&&in_array($mode,['answer','drawing'],true)&&$a['type']!=='choice')echo '<div class="speak-row"><button type="button" class="btn secondary" id="recognize">'.icon('mic').'Speak Answer</button><button type="button" class="btn quiet" id="type-answer">'.icon('edit').'Type Answer</button><span id="speech-status" role="status">Choose either way to answer.</span></div><p class="speech-note">The microphone may mishear. Check the detected text before submitting.</p><div id="word-feedback" aria-live="polite"></div>';
  echo '<div id="answer-feedback" role="status" aria-live="polite" class="answer-feedback '.($readonly?'success':'').'">'.($readonly?icon('check').'<div><strong>'.($exact?'Correct!':'Saved. Well done!').'</strong><p>Your progress is saved. You can continue.</p></div>':'').'</div><div class="activity-bottom"><div><span id="draft-status" role="status">'.($draft?'Draft restored':($mode==='none'?'No answer needed on this page.':'Your work saves automatically.')).'</span>'.source_link((int)$a['source_page'],(int)$a['lesson_id']).'</div>';
  if(!$readonly)echo '<button id="submit-answer" class="btn primary next" type="submit">'.($mode==='none'?'Next':($mode==='perform'?'Done':($exact?'Check Answer':'Submit Answer'))).' '.icon($mode==='perform'?'check':'arrow').'</button>';
  echo '<a id="next-activity" class="btn primary next" href="?page=lesson&id='.$lid.'" '.(!$readonly?'hidden':'').'>'.($done===count($all)?'Finish Lesson':'Next').' '.icon('arrow').'</a></div></form>';
 }
 echo '<details class="lesson-outline"><summary>Lesson activities and saved work</summary>';foreach($all as $a){$enabled=completion_ok($a);echo '<div>'.($enabled?'<a href="?page=lesson&id='.$lid.'&activity='.$a['id'].'">':'<span>').e(ucfirst($a['phase']).' · '.$a['title']).($enabled?'</a>':'</span>').'<span class="status '.e($a['status']??'').'">'.($enabled?'Complete':($a['status']==='retry'?'Try again':'Not started')).'</span></div>';}echo '</details></main>';foot();
}
function teacher_dashboard(array $u):void{
 echo '<section class="card demo-entry"><div><span class="eyebrow">FOR THE WHOLE CLASS</span><h2>Learn together on the big screen.</h2><p>Open any activity, listen, and move at your class’s pace.</p></div><a class="btn primary" href="?page=class_demo">Open Class Demo '.icon('arrow').'</a></section>';
 [$grade,$sid]=teacher_class_selection($u);
 section_filter($u,'dashboard',$sid,$grade);
 $pupils=rows('SELECT u.*,p.grade_level,p.section,l.title level_title FROM users u JOIN pupils p ON p.user_id=u.id JOIN teacher_pupils t ON t.pupil_id=u.id JOIN pupil_level_assignments a ON a.pupil_id=u.id JOIN bulig_levels l ON l.id=a.level_id WHERE t.teacher_id=? AND p.grade_level=? AND (?=0 OR u.id IN(SELECT pupil_id FROM pupil_sections WHERE section_id=?)) ORDER BY u.name',[$u['id'],$grade,$sid,$sid]);$pending=(int)val("SELECT COUNT(*) FROM activity_completion c JOIN teacher_pupils t ON t.pupil_id=c.pupil_id JOIN pupils p ON p.user_id=c.pupil_id WHERE t.teacher_id=? AND p.grade_level=? AND (?=0 OR c.pupil_id IN(SELECT pupil_id FROM pupil_sections WHERE section_id=?)) AND c.status IN ('completed','approved')",[$u['id'],$grade,$sid,$sid]);
 echo '<div class="pageheading"><div><span class="eyebrow">TEACHER OVERVIEW</span><h1>Every learner matters.</h1><p class="muted">A clear view of your pupils’ next steps.</p></div><a class="btn primary" href="?page=accounts">'.icon('people').'Add a pupil</a></div><div class="statgrid"><div class="stat">'.icon('people').'<div><strong>'.count($pupils).'</strong><span>Your pupils</span></div></div><div class="stat">'.icon('clock').'<div><strong>'.$pending.'</strong><span>Completed activities</span></div></div><div class="stat">'.icon('book').'<div><strong>'.(int)val('SELECT COUNT(*) FROM lessons WHERE published=1').'</strong><span>Available learning steps</span></div></div></div><section class="card"><div class="section-heading"><h2>Grade '.$grade.' · Class overview</h2><a href="?page=review">View activity history '.icon('arrow').'</a></div><div class="tablewrap"><table><thead><tr><th>Pupil</th><th>Grade / section</th><th>Starting level</th><th>Progress</th><th>XP / streak</th><th>Last learning day</th><th>Status</th></tr></thead><tbody>';
 foreach($pupils as $p){$s=progress_stats((int)$p['id']);$inactive=!$s['last_activity_date']||$s['last_activity_date']<date('Y-m-d',strtotime('-7 days'));echo '<tr><td><a href="?page=pupil&id='.$p['id'].'"><strong>'.e($p['name']).'</strong></a><small>'.e($p['public_id']).'</small></td><td>'.e($p['grade_level'].' / '.$p['section']).'</td><td>'.e($p['level_title']).'</td><td>'.$s['completed'].' learning steps completed</td><td>'.$s['xp'].' XP<small>'.$s['current_streak'].' days · best '.$s['longest_streak'].'</small></td><td>'.e($s['last_activity_date']??'Not yet').'</td><td><span class="status">'.(!$p['active']?'Inactive account':($inactive?'Needs a check-in':'Learning')).'</span></td></tr>';}
 if(!$pupils)echo '<tr><td colspan="7">No pupils in this selection yet. Choose another section or add a pupil.</td></tr>';echo '</tbody></table></div></section>';
}
function accounts_view(array $u):void{
 $isAdmin=$u['role']==='admin';$people=$isAdmin?rows("SELECT * FROM users WHERE role='teacher' ORDER BY created_at DESC"):rows('SELECT u.*,p.grade_level,p.section,a.level_id,ps.section_id,pd.sex,pd.lrn FROM users u JOIN pupils p ON p.user_id=u.id JOIN teacher_pupils t ON t.pupil_id=u.id JOIN pupil_level_assignments a ON a.pupil_id=u.id LEFT JOIN pupil_sections ps ON ps.pupil_id=u.id LEFT JOIN pupil_details pd ON pd.pupil_id=u.id WHERE t.teacher_id=? ORDER BY u.created_at DESC',[$u['id']]);$levels=$isAdmin?[]:teacher_sections((int)$u['id']);
 echo '<div class="pageheading"><div><span class="eyebrow">ACCOUNT MANAGEMENT</span><h1>'.($isAdmin?'Your teaching team':'Your pupils').'</h1><p class="muted">Create accounts, set passwords, and keep learner details up to date.</p></div></div><section class="card"><h2>Create a '.($isAdmin?'teacher':'pupil').' account</h2><form class="formgrid" method="post">'.csrf_field().'<input type="hidden" name="action" value="create_account"><label>Full name<input name="name" required maxlength="150"></label>';if($isAdmin)echo '<label>Password<input name="password" type="password" required minlength="8" maxlength="72" autocomplete="new-password"></label>';else echo '<div class="default-password"><strong>Default pupil password</strong><p>12345678</p><small>The pupil may keep it or change it in My profile.</small></div>';
 if(!$isAdmin)echo grade_fields([], $levels);echo '<div class="formend"><small>A unique '.($isAdmin?'Teacher':'Pupil').' ID is generated automatically.</small><button class="btn primary" type="submit">Create account '.icon('arrow').'</button></div></form></section><section class="card"><h2>'.count($people).' '.($isAdmin?'teachers':'pupils').'</h2>';
 foreach($people as $p){echo '<details class="account-detail"><summary>'.avatar($p).'<span><strong>'.e($p['name']).'</strong><small>'.e($p['public_id']).'</small></span><span class="status">'.($p['active']?'Active':'Inactive').'</span></summary><form method="post" class="formgrid">'.csrf_field().'<input type="hidden" name="action" value="update_account"><input type="hidden" name="id" value="'.$p['id'].'"><label>Full name<input name="name" value="'.e($p['name']).'" required maxlength="150"></label><label>New password (optional)<input name="password" type="password" minlength="8" maxlength="72" autocomplete="new-password"></label>';if(!$isAdmin)echo grade_fields($p,$levels);echo '<label class="checkbox"><input type="checkbox" name="active" '.($p['active']?'checked':'').'>Account active</label><button class="btn primary" type="submit">Save changes</button></form></details>';}
 echo '</section>';
}
function grade_fields(array $p,array $sections):string{
 $s='<label>Section<select name="section_id" required><option value="">Choose a section</option>';foreach($sections as $section)$s.='<option value="'.$section['id'].'" '.(($p['section_id']??0)==$section['id']?'selected':'').'>Grade '.$section['grade_level'].' · '.e($section['name']).'</option>';
 $s.='</select></label>'; $s.=pupil_details_fields($p); $s.=starting_level_field((int)($p['level_id']??1));
 return $s.'<div class="section-help"><a href="?page=sections">Add or edit your sections</a><p class="muted">Grade follows the section. Starting level is chosen separately: any Grade 1–6 pupil can start at any level. Future content stays locked.</p></div>';
}
function review_view(array $u):void{
 $historyPage=max(1,(int)($_GET['p']??1));$historyOffset=($historyPage-1)*30;
 echo '<div class="pageheading"><div><span class="eyebrow">TEACHER REVIEW</span><h1>A little feedback goes a long way.</h1><p class="muted">View completed work and leave optional feedback. Pupils continue immediately.</p></div></div>';
 $ready=rows("SELECT aa.*,a.lesson_id,a.title,a.rubric,a.rubric_criteria,a.source_page,u.name,u.public_id FROM assessment_attempts aa JOIN assessments a ON a.id=aa.assessment_id JOIN teacher_pupils t ON t.pupil_id=aa.pupil_id JOIN users u ON u.id=aa.pupil_id WHERE t.teacher_id=? AND aa.status='submitted' AND NOT EXISTS(SELECT 1 FROM activities act LEFT JOIN activity_completion c ON c.activity_id=act.id AND c.pupil_id=aa.pupil_id WHERE act.assessment_id=a.id AND act.published=1 AND (c.status IS NULL OR c.status NOT IN ('approved','completed')))",[$u['id']]);
 foreach($ready as $r){echo '<section class="card assessment-review"><span class="eyebrow">OPTIONAL ASSESSMENT FEEDBACK</span><h2>'.e($r['name'].' · '.$r['title']).'</h2>'.source_link((int)$r['source_page'],(int)$r['lesson_id']).'<details><summary>Read the original assessment and rubric (optional scoring)</summary><pre class="source-text">'.e($r['rubric']).'</pre></details><form method="post" class="stack">'.csrf_field().'<input type="hidden" name="action" value="review_assessment"><input type="hidden" name="pupil_id" value="'.$r['pupil_id'].'"><input type="hidden" name="assessment_id" value="'.$r['assessment_id'].'">';$criteria=json_decode($r['rubric_criteria']??'[]',true)?:[];foreach($criteria as $i=>$c)echo '<label>'.e($c).'<select name="scores['.$i.']" required><option value="">Select rating from original rubric</option><option value="1">1 · Needs improvement</option><option value="2">2 · Satisfactory</option><option value="3">3 · Good</option><option value="4">4 · Excellent</option></select></label>';if(!$criteria)echo '<p>No numeric rubric is supplied for this assessment. Confirm completion based on teacher observation.</p>';echo '<label>Feedback<textarea name="feedback" maxlength="3000"></textarea></label><button class="btn primary">Save optional assessment feedback</button></form></section>';}
 $pending=rows("SELECT c.*,a.lesson_id,a.image_path,a.title,a.source_page,a.type,a.expected_text,l.subtitle,u.name,u.public_id FROM activity_completion c JOIN activities a ON a.id=c.activity_id JOIN lessons l ON l.id=a.lesson_id JOIN teacher_pupils t ON t.pupil_id=c.pupil_id JOIN users u ON u.id=c.pupil_id WHERE t.teacher_id=? AND c.status IN ('completed','approved') ORDER BY c.submitted_at DESC,c.id DESC LIMIT 30 OFFSET ".$historyOffset,[$u['id']]);
 foreach($pending as $r){echo '<section class="card review-card"><div class="section-heading"><div><span class="eyebrow">'.e($r['name'].' · '.$r['public_id']).'</span><h2>'.e($r['subtitle'].' · '.$r['title']).'</h2></div><span class="status">'.e($r['type']).'</span></div><details><summary>Prompt and original instructions</summary><p class="preserve">'.e($r['prompt_snapshot']).'</p>'.source_link((int)$r['source_page'],(int)$r['lesson_id']).'</details><blockquote>'.nl2br(e($r['response'])).'</blockquote>';if($r['drawing']){echo '<div class="review-worksheet">';if(in_array(lesson_level((int)$r['lesson_id']),[2,3],true)&&local_image_file((string)$r['image_path']))echo '<img class="review-sheet" src="'.e($r['image_path']).'" alt="Original worksheet">';echo '<img class="submitted-drawing" src="'.e($r['drawing']).'" alt="Pupil’s drawing"></div>';}$read=one('SELECT * FROM reading_assessments WHERE pupil_id=? AND activity_id=? ORDER BY id DESC LIMIT 1',[$r['pupil_id'],$r['activity_id']]);if($read)echo '<p>Recognized words: '.e($read['transcript']).'</p><p class="muted">Word match: '.e($read['word_match_percent']).'%. This measures recognized text, not pronunciation.</p>';echo '<form method="post" class="stack">'.csrf_field().'<input type="hidden" name="action" value="review"><input type="hidden" name="completion_id" value="'.$r['id'].'"><label>Helpful feedback<textarea name="feedback" maxlength="3000" placeholder="Tell the pupil what went well or how to try again."></textarea></label><div class="buttonrow"><button class="btn primary">'.icon('check').'Save feedback</button></div></form></section>';}
 echo '<nav class="buttonrow"><a class="btn quiet" href="?page=review&p='.max(1,$historyPage-1).'">Previous page</a><span>Page '.$historyPage.'</span><a class="btn quiet" href="?page=review&p='.($historyPage+1).'">Next page</a></nav>';
 if(!$pending&&!$ready)echo '<section class="empty">'.icon('check').'<h2>You’re all caught up.</h2><p>Completed pupil responses will appear here.</p></section>';
}
function achievements_view(array $u):void{
 $s=progress_stats((int)$u['id']);echo '<div class="pageheading"><div><span class="eyebrow">YOUR ACHIEVEMENTS</span><h1>Look how far you’ve come.</h1><p class="muted">'.$s['xp'].' XP earned, one meaningful activity at a time.</p></div></div><div class="badgegrid">';foreach(rows('SELECT b.*,p.earned_at FROM badges b LEFT JOIN pupil_badges p ON p.badge_id=b.id AND p.pupil_id=? WHERE b.active=1 ORDER BY b.id',[$u['id']]) as $b)echo '<section class="card badgecard '.($b['earned_at']?'earned':'not-earned').'"><span class="medal">'.icon($b['earned_at']?'star':'lock').'</span><h2>'.e($b['title']).'</h2><p>'.e($b['description']).'</p><small>'.($b['earned_at']?'Earned '.e(substr($b['earned_at'],0,10)):'Keep going — you’ll get there.').'</small></section>';echo '</div><h2>Your rewards</h2><div class="badgegrid">';foreach(rows('SELECT r.*,p.earned_at FROM rewards r LEFT JOIN pupil_rewards p ON p.reward_id=r.id AND p.pupil_id=? WHERE r.active=1',[$u['id']]) as $r)echo '<section class="card"><h3>'.icon('bolt').e($r['title']).'</h3><p>'.$r['required_xp'].' XP · '.($r['earned_at']?'Earned':'In progress').'</p><progress value="'.min($s['xp'],(int)$r['required_xp']).'" max="'.max(1,(int)$r['required_xp']).'"></progress></section>';echo '</div>';
}
function admin_dashboard():void{
 echo '<div class="pageheading"><div><span class="eyebrow">ADMINISTRATOR OVERVIEW</span><h1>Make room for learning.</h1><p class="muted">Official content, thoughtful teaching, and one connected workspace.</p></div><a class="btn primary" href="?page=content">Open lesson studio '.icon('arrow').'</a></div><div class="statgrid">';foreach([['book','Lessons','SELECT COUNT(*) FROM lessons'],['people','Teachers',"SELECT COUNT(*) FROM users WHERE role='teacher'"],['flag','Content notes to review','SELECT COUNT(*) FROM content_issues WHERE acknowledged_at IS NULL']] as $v)echo '<section class="stat">'.icon($v[0]).'<div><strong>'.(int)val($v[2]).'</strong><span>'.$v[1].'</span></div></section>';echo '</div><section class="card"><span class="eyebrow">LEVEL 1 · ORAL LANGUAGE</span><h2>The official module comes first.</h2><p>Level 1, Level 2A and Level 2B learning steps with original worksheet visuals. Edit activities in Lesson Studio, inspect source pages, and record decisions about the module’s inconsistencies.</p><div class="buttonrow"><a class="btn secondary" href="?page=content">'.icon('edit').'Manage lessons</a><a class="btn quiet" href="?page=issues">'.icon('flag').'Review content notes</a></div></section><section class="card"><h2>Recent administration</h2><div class="tablewrap"><table><thead><tr><th>Action</th><th>Reference</th><th>When</th></tr></thead><tbody>';foreach(rows('SELECT * FROM audit_log ORDER BY id DESC LIMIT 12') as $a)echo '<tr><td>'.e($a['action']).'</td><td>'.e($a['details']).'</td><td>'.e($a['created_at']).'</td></tr>';echo '</tbody></table></div></section>';
}
function content_view():void{
 $lid=(int)($_GET['id']??1);$l=one('SELECT * FROM lessons WHERE id=?',[$lid]);if(!$l)fail('Lesson not found.',404);echo '<div class="pageheading"><div><span class="eyebrow">LESSON STUDIO</span><h1>Thoughtfully prepared. Ready to learn.</h1><p class="muted">Edit learning content and narration. Keep the official module open as your reference.</p></div></div><nav class="lesson-tabs">';foreach(rows('SELECT l.*,m.level_id FROM lessons l JOIN modules m ON m.id=l.module_id ORDER BY m.level_id,l.position') as $item)echo '<a class="'.($item['id']==$lid?'active':'').'" href="?page=content&id='.$item['id'].'">'.$item['position'].'</a>';echo '</nav><section class="card"><div class="section-heading"><h2>Lesson '.$l['position'].' · '.e($l['subtitle']).'</h2><a href="?page=guide&id='.$lid.'">Teacher’s guide</a></div><form method="post" class="formgrid">'.csrf_field().'<input type="hidden" name="action" value="save_lesson"><input type="hidden" name="id" value="'.$lid.'"><label>Official title<input name="title" value="'.e($l['title']).'" required maxlength="255"></label><label>Short screen title<input name="subtitle" value="'.e($l['subtitle']).'" maxlength="255"></label><label class="wide">Objectives<textarea name="objectives" rows="4">'.e($l['objectives']).'</textarea></label><label>Cover image path<input name="image_path" value="'.e($l['image_path']).'"></label><label class="checkbox"><input type="checkbox" name="published" '.($l['published']?'checked':'').'>Published</label><button class="btn primary">Save lesson</button></form></section><section class="card"><h2>Learning sequence</h2><div class="tablewrap"><table><thead><tr><th>Stage</th><th>Activity</th><th>Format</th><th>XP</th><th>Source</th><th></th></tr></thead><tbody>';
 foreach(rows("SELECT * FROM activities WHERE lesson_id=? ORDER BY FIELD(phase,'pre','learn','post'),position",[$lid]) as $a)echo '<tr><td>'.e(ucfirst($a['phase'])).' '.$a['position'].'</td><td>'.e($a['title']).(!$a['published']?' · Draft':'').'</td><td>'.e($a['type']).'</td><td>'.$a['xp_reward'].'</td><td>PDF '.$a['source_page'].'</td><td><a href="?page=edit_activity&id='.$a['id'].'">Edit '.icon('edit').'</a></td></tr>';echo '</tbody></table></div></section>';
 foreach(rows('SELECT * FROM assessments WHERE lesson_id=?',[$lid]) as $a){echo '<details class="card"><summary>'.e($a['title']).' · Assessment rubric</summary><form method="post" class="stack">'.csrf_field().'<input type="hidden" name="action" value="save_assessment"><input type="hidden" name="id" value="'.$a['id'].'"><input type="hidden" name="lesson_id" value="'.$lid.'">'.source_link((int)$a['source_page'],(int)$a['lesson_id']).'<label>Original rubric / assessment<textarea name="rubric" rows="12">'.e($a['rubric']).'</textarea></label><label>Numeric rubric criteria (one per line; leave empty if none is supplied)<textarea name="criteria">'.e(implode("\n",json_decode($a['rubric_criteria']??'[]',true)?:[])).'</textarea></label><button class="btn primary">Save rubric</button></form></details>';}
}
function edit_activity_view():void{
 $a=one('SELECT * FROM activities WHERE id=?',[(int)($_GET['id']??0)]);if(!$a)fail('Activity not found.',404);$question=one('SELECT * FROM questions WHERE activity_id=?',[$a['id']]);$ans=rows('SELECT * FROM answers WHERE question_id=?',[$question['id']]);
 echo '<div class="pageheading"><div><a href="?page=content&id='.$a['lesson_id'].'">Back to lesson '.$a['lesson_id'].'</a><h1>'.e($a['title']).'</h1><p class="muted">'.e($a['phase']).' · Activity '.$a['position'].' · Revision '.$a['revision'].'</p></div>'.source_link((int)$a['source_page'],(int)$a['lesson_id']).'</div><section class="card"><form method="post" class="formgrid">'.csrf_field().'<input type="hidden" name="action" value="save_activity"><input type="hidden" name="id" value="'.$a['id'].'"><label>Title<input name="title" value="'.e($a['title']).'" required maxlength="255"></label><label>Activity format<select name="type">';foreach(['open','sentence','reading','physical','group','drawing','choice','exact','reference'] as $t)echo '<option '.($a['type']===$t?'selected':'').'>'.$t.'</option>';echo '</select></label><label>Interaction<select name="response_mode">';foreach(['answer'=>'Speak or type an answer','none'=>'Read / listen, then Next','perform'=>'Practical activity, then Done','drawing'=>'Draw or describe'] as $key=>$label)echo '<option value="'.$key.'" '.($a['response_mode']===$key?'selected':'').'>'.e($label).'</option>';echo '</select></label><label class="wide">Instructions<textarea name="instructions" rows="3">'.e($a['instructions']).'</textarea></label><label class="wide">Prompt<textarea name="prompt" rows="6" required>'.e($a['prompt']).'</textarea></label><label class="wide">Narration text<textarea name="narration" rows="5">'.e($a['narration']).'</textarea></label><label class="wide">Official image paths (one per line)<textarea name="image_paths" rows="3">'.e(implode("\n",json_decode($a['image_paths']??'[]',true)?:[])).'</textarea></label><label class="wide">Expected reading text (for word matching only)<textarea name="expected_text" rows="3">'.e($a['expected_text']).'</textarea></label><label>Grading<select name="grading"><option value="teacher" '.($question['grading']==='teacher'?'selected':'').'>Personal response · record completion</option><option value="exact" '.($question['grading']==='exact'?'selected':'').'>Automatic checking · official answer</option></select></label><label>XP on completion<input type="number" name="xp_reward" min="0" max="1000" value="'.$a['xp_reward'].'" required></label><label>Answer choices (one per line)<textarea name="options" rows="4">'.e(implode("\n",array_column($ans,'content'))).'</textarea></label><label>Accepted answers (one per line)<textarea name="answers" rows="4">'.e(implode("\n",array_column(array_filter($ans,fn($v)=>$v['correct']),'content'))).'</textarea></label><label class="checkbox"><input type="checkbox" name="published" '.($a['published']?'checked':'').'>Published</label><div class="formend"><small>Personal answers are recorded without a correctness score. Exact grading requires a verified answer key.</small><button class="btn primary">Save activity '.icon('check').'</button></div></form></section>';
}
function media_view():void{
 echo '<section class="card"><h2>Check activity pictures</h2><p>Check this server for missing files, empty picture assignments and images that need a teacher-supplied example.</p><a class="btn primary" href="?page=visual_audit">Run image check</a></section>';
 $n=max(1,min(95,(int)($_GET['n']??16)));$p=one('SELECT * FROM source_pages WHERE page_number=?',[$n]);echo '<div class="pageheading"><div><span class="eyebrow">OFFICIAL VISUALS</span><h1>Every picture belongs.</h1><p class="muted">Original embedded images, extracted without replacement or redrawing.</p></div></div><section class="card"><form method="get" class="buttonrow"><input type="hidden" name="page" value="media"><label>PDF page<input type="number" name="n" min="1" max="95" value="'.$n.'"></label><button class="btn primary">View page</button>'.source_link($n).'</form></section><div class="mediagrid">';foreach(json_decode($p['images'],true) as $im)echo '<section class="card"><img src="'.e($im['path']).'" alt="Extracted official image"><label>Image path<input readonly value="'.e($im['path']).'"></label><small>'.$im['width'].' × '.$im['height'].' pixels</small></section>';echo '</div><section class="card"><h2>Add an approved visual</h2><form method="post" enctype="multipart/form-data" class="buttonrow">'.csrf_field().'<input type="hidden" name="action" value="upload_media"><label>PNG, JPEG, or WebP · up to 4 MB<input name="media" type="file" accept="image/png,image/jpeg,image/webp" required></label><button class="btn primary">Upload image</button></form></section>';
}
function guide_view():void{
 $lid=(int)($_GET['id']??1);$l=one('SELECT * FROM lessons WHERE id=?',[$lid]);if(!$l)fail('Lesson not found.',404);$level=lesson_level($lid);
 echo '<div class="pageheading"><div><span class="eyebrow">TEACHER’S GUIDE</span><h1>Teach with the source beside you.</h1><p class="muted">Original instructions, worksheets, assessments, and teacher-only keys.</p></div></div><form method="get" class="card"><input type="hidden" name="page" value="guide"><label>Choose a learning step<select name="id">';
 foreach(rows('SELECT l.*,m.level_id FROM lessons l JOIN modules m ON m.id=l.module_id ORDER BY m.level_id,l.position') as $x)echo '<option value="'.$x['id'].'" '.($x['id']==$lid?'selected':'').'>'.e(level_label((int)$x['level_id']).' · '.$x['position'].' · '.$x['subtitle']).'</option>';
 echo '</select></label><button class="btn primary">Open guide</button></form><section class="card"><h2>'.e(level_label($level).' · '.$l['title']).'</h2><p>'.e($l['objectives']).'</p><div class="source-pages">';foreach(json_decode($l['source_pages'],true) as $n)echo source_link($n,$lid);
 echo '</div><details open><summary>Complete lesson plan text</summary><pre class="source-text">'.e($l['teacher_guide']).'</pre></details><a class="btn secondary" href="?page=download_source&level='.$level.'">Download original '.e(level_label($level)).' module</a></section>';
 if($level>1)echo '<section class="card"><h2>About online completion</h2><p>The worksheets record typed answers and drawings without automatic correctness scores. Optional teacher feedback does not block progression. Use the original PDF for the separate timed oral protocol and its answer key. Some module examples are inconsistent; review Content Notes with your administrator.</p></section>';
}

function issues_view():void{
 echo '<div class="pageheading"><div><span class="eyebrow">SOURCE INTEGRITY</span><h1>Keep the original. Record the decision.</h1><p class="muted">These issues come from the supplied module. Record the approved classroom interpretation here.</p></div></div>';foreach(rows('SELECT * FROM content_issues ORDER BY id') as $i)echo '<section class="card"><span class="status">'.($i['acknowledged_at']?'Reviewed':'Needs review').'</span><p>'.e($i['description']).'</p><form method="post" class="stack">'.csrf_field().'<input type="hidden" name="action" value="acknowledge"><input type="hidden" name="id" value="'.$i['id'].'"><label>Administrator’s decision<textarea name="resolution" required maxlength="3000">'.e($i['resolution']).'</textarea></label><button class="btn primary">Record decision</button></form></section>';
}
function settings_view():void{
 echo '<div class="pageheading"><div><span class="eyebrow">LEARNING REWARDS</span><h1>Celebrate meaningful progress.</h1><p class="muted">Rewards recognize completed learning. XP never skips an activity or assessment.</p></div></div><h2>Badges</h2>';foreach(rows('SELECT * FROM badges') as $b)echo '<details class="card"><summary>'.e($b['title']).' · '.e($b['rule_type']).'</summary><form method="post" class="formgrid">'.csrf_field().'<input type="hidden" name="action" value="save_badge"><input type="hidden" name="id" value="'.$b['id'].'"><label>Title<input name="title" value="'.e($b['title']).'" required maxlength="100"></label><label>Threshold<input type="number" name="threshold_value" min="1" value="'.$b['threshold_value'].'" required></label><label>Description<input name="description" value="'.e($b['description']).'" maxlength="255"></label><label class="checkbox"><input type="checkbox" name="active" '.($b['active']?'checked':'').'>Active</label><button class="btn primary">Save badge</button></form></details>';echo '<h2>XP rewards</h2>';foreach(rows('SELECT * FROM rewards') as $r)echo '<section class="card"><form method="post" class="formgrid">'.csrf_field().'<input type="hidden" name="action" value="save_reward"><input type="hidden" name="id" value="'.$r['id'].'"><label>Title<input name="title" value="'.e($r['title']).'" required maxlength="100"></label><label>Required XP<input name="required_xp" type="number" min="0" value="'.$r['required_xp'].'" required></label><label class="checkbox"><input name="active" type="checkbox" '.($r['active']?'checked':'').'>Active</label><button class="btn primary">Save reward</button></form></section>';
}
function pupil_detail():void{
 $pid=(int)($_GET['id']??0);own_pupil($pid);$p=one('SELECT * FROM users WHERE id=?',[$pid]);$s=progress_stats($pid);echo '<div class="pageheading"><div><span class="eyebrow">PUPIL PROGRESS · '.e($p['public_id']).'</span><h1>'.e($p['name']).'</h1><p class="muted">'.$s['xp'].' XP · '.$s['completed'].' lessons complete · '.$s['current_streak'].' day streak</p></div></div><section class="card"><h2>Assessment results</h2><div class="tablewrap"><table><thead><tr><th>Assessment</th><th>Status</th><th>Score</th><th>Teacher feedback</th></tr></thead><tbody>';foreach(rows('SELECT aa.*,a.title FROM assessment_attempts aa JOIN assessments a ON a.id=aa.assessment_id WHERE aa.pupil_id=? ORDER BY a.lesson_id,a.id',[$pid]) as $a)echo '<tr><td>'.e($a['title']).'</td><td>'.e($a['status']).'</td><td>'.($a['score']!==null?e($a['score'].' / '.$a['max_score']):'Observation-based').'</td><td>'.e($a['feedback']).'</td></tr>';echo '</tbody></table></div></section><section class="card"><h2>Recent learning</h2><div class="tablewrap"><table><thead><tr><th>Lesson / activity</th><th>Answer</th><th>Status</th><th>Date</th></tr></thead><tbody>';foreach(rows('SELECT c.*,a.title,l.subtitle FROM activity_completion c JOIN activities a ON a.id=c.activity_id JOIN lessons l ON l.id=a.lesson_id WHERE c.pupil_id=? ORDER BY c.submitted_at DESC LIMIT 100',[$pid]) as $c)echo '<tr><td>'.e($c['subtitle'].' / '.$c['title']).'</td><td>'.e($c['response']).'</td><td>'.e($c['status']).'</td><td>'.e($c['submitted_at']).'</td></tr>';echo '</tbody></table></div></section><section class="card"><h2>Reading word matches</h2><p class="muted">Recognized-text similarity is not a pronunciation score.</p>';foreach(rows('SELECT r.*,a.title FROM reading_assessments r JOIN activities a ON a.id=r.activity_id WHERE r.pupil_id=? ORDER BY r.id DESC LIMIT 20',[$pid]) as $r)echo '<details><summary>'.e($r['title'].' · '.$r['word_match_percent'].'%').'</summary><p>'.e($r['transcript']).'</p></details>';echo '</section><section class="card"><h2>Earned badges</h2>';foreach(rows('SELECT b.title FROM pupil_badges p JOIN badges b ON b.id=p.badge_id WHERE p.pupil_id=?',[$pid]) as $b)echo '<span class="status">'.icon('star').e($b['title']).'</span>';echo '</section>';
}
function profile_view(array $u):void{
 if($u['role']==='pupil')avatar_picker($u);
 echo '<div class="pageheading"><div><span class="eyebrow">MY PROFILE</span><h1>'.e($u['name']).'</h1><p class="muted">'.e($u['public_id']).' · '.e(ucfirst($u['role'])).'</p></div>'.avatar($u).'</div><section class="card"><h2>Upload your own photo</h2><form method="post" enctype="multipart/form-data" class="stack">'.csrf_field().'<input type="hidden" name="action" value="profile"><label>Choose a PNG, JPEG, or WebP image (up to 4 MB)<input name="avatar" type="file" accept="image/png,image/jpeg,image/webp" required></label><button class="btn primary">Save photo</button></form></section>';if($u['role']==='pupil'){echo '<section class="card"><h2>This week</h2><div class="weekdays">';$days=array_column(rows('SELECT day FROM learning_days WHERE pupil_id=? AND day>=?',[$u['id'],date('Y-m-d',strtotime('-6 days'))]),'day');for($i=6;$i>=0;$i--){$d=date('Y-m-d',strtotime('-'.$i.' days'));echo '<div class="weekday '.(in_array($d,$days)?'active':'').'"><span>'.date('D',strtotime($d)).'</span>'.icon(in_array($d,$days)?'check':'clock').'</div>';}echo '</div><p class="muted">A day counts when you complete a meaningful answer or practical activity.</p></section>';}
 password_change_form();
}
function teacher_class_selection(array $u):array{
 $sid=max(0,(int)($_GET['section_id']??0));$section=$sid?owned_section($sid,(int)$u['id']):null;
 $sections=teacher_sections((int)$u['id']);
 $grade=(int)($_GET['grade_level']??($section['grade_level']??($sections[0]['grade_level']??1)));
 if($grade<1||$grade>6)fail('Choose a grade from 1 to 6.');
 if($section&&(int)$section['grade_level']!==$grade)fail('Choose a section in the selected grade.');
 return [$grade,$sid];
}
function section_filter(array $u,string $page,int $selected,int $grade):void{
 echo '<form class="section-filter class-picker" method="get"><input type="hidden" name="page" value="'.e($page).'"><div class="class-picker-intro"><span class="eyebrow">YOUR CLASSROOM</span><strong>Choose a grade, then a section</strong></div><label>Grade level<select name="grade_level" data-grade-filter>';
 for($g=1;$g<=6;$g++)echo '<option value="'.$g.'" '.($grade===$g?'selected':'').'>Grade '.$g.'</option>';
 echo '</select></label><label>Section<select name="section_id" data-section-filter><option value="0">All Grade '.$grade.' sections</option>';
 foreach(teacher_sections((int)$u['id']) as $section)if((int)$section['grade_level']===$grade)echo '<option value="'.$section['id'].'" '.($selected==(int)$section['id']?'selected':'').'>'.e($section['name']).'</option>';
 echo '</select></label><button class="btn secondary">Show pupils</button><a class="btn quiet" href="?page=sections">Manage sections</a></form>';
}
function sections_view(array $u):void{
 echo '<div class="pageheading"><div><span class="eyebrow">YOUR CLASSES</span><h1>A place for every pupil.</h1><p class="muted">Add the sections you handle, then choose a section when creating a pupil.</p></div></div><section class="card"><h2>Add a section</h2><form method="post" class="formgrid">'.csrf_field().'<input name="action" type="hidden" value="save_section"><label>Section name<input name="name" maxlength="80" required></label><label>Grade<select name="grade_level">';for($i=1;$i<=6;$i++)echo '<option value="'.$i.'">Grade '.$i.'</option>';echo '</select></label><button class="btn primary">Add section</button></form></section>';
 foreach(teacher_sections((int)$u['id']) as $s){$count=(int)val('SELECT COUNT(*) FROM pupil_sections WHERE section_id=?',[$s['id']]);echo '<section class="card"><div class="section-heading"><h2>Grade '.$s['grade_level'].' · '.e($s['name']).'</h2><a href="?page=dashboard&section_id='.$s['id'].'">'.$count.' pupils '.icon('arrow').'</a></div><details><summary>Edit section</summary><form method="post" class="formgrid">'.csrf_field().'<input name="action" type="hidden" value="save_section"><input name="id" type="hidden" value="'.$s['id'].'"><label>Name<input name="name" value="'.e($s['name']).'" required maxlength="80"></label><label>Grade<select name="grade_level">';for($i=1;$i<=6;$i++)echo '<option value="'.$i.'" '.($s['grade_level']==$i?'selected':'').'>Grade '.$i.'</option>';echo '</select></label><button class="btn primary">Save section</button></form></details></section>';}
}

function starting_level_field(int $selected):string{
 $s='<label>Starting level<select name="level_id" required>';
 foreach(rows('SELECT id,published FROM bulig_levels ORDER BY id') as $l)$s.='<option value="'.$l['id'].'" '.($selected==(int)$l['id']?'selected':'').'>'.e(level_label((int)$l['id'])).($l['published']?((int)$l['id']===1?' · Oral Language':' · Phonological Awareness'):' · content not available yet').'</option>';
 return $s.'</select></label>';
}
function level_cards(?array $assigned):void{
 $pid=(int)current_user()['id'];$start=(int)($assigned['id']??0);echo '<section class="level-catalog" aria-label="BULIG levels"><div class="section-heading"><div><span class="eyebrow">ONE LITTLE STEP AT A TIME</span><h2>Your learning adventures</h2></div><p>Starting level: <strong>'.e(level_label($start)).'</strong></p></div><div class="level-card-grid">';
 foreach(rows('SELECT * FROM bulig_levels ORDER BY id') as $l){$id=(int)$l['id'];$available=level_available($pid,$id);$count=(int)val('SELECT COUNT(*) FROM lessons l JOIN modules m ON m.id=l.module_id WHERE m.level_id=? AND l.published=1',[$id]);
 echo '<article class="level-card '.($available?'available':'unavailable').' level-tone-'.$id.'"><div class="level-cover"><span class="level-number">'.e(str_replace('Level ','',level_label($id))).'</span><span class="cover-symbol">'.icon($available?'sound':'lock').'</span><span class="cover-caption">'.($available?'LET’S EXPLORE TOGETHER':'A NEW ADVENTURE AWAITS').'</span></div><div class="level-card-content"><div class="level-card-heading"><h3>'.e(level_label($id)).'</h3>'.($start===$id?'<span class="status">Your starting level</span>':'').'</div><p>'.e($l['published']?$l['title']:'More learning is on the way.').'</p><small>'.($l['published']?$count.' learning steps':'Activities are being prepared').'</small>'.($available?'<a class="btn primary" href="?page=dashboard&amp;level='.$id.'#level'.$id.'-path">Open lessons '.icon('arrow').'</a>':'<span class="level-lock">'.icon('lock').(!$l['published']?'Locked · coming soon':($id<$start?'Before your starting level':'Finish the earlier level first')).'</span>').'</div></article>';
 }echo '</div></section>';
}

function password_change_form():void{
 echo '<section class="card"><h2>Change password</h2><p>This is optional. You can keep your current password.</p><form method="post" class="formgrid">'.csrf_field().'<input type="hidden" name="action" value="change_password"><label>Current password<input name="current_password" type="password" autocomplete="current-password" required maxlength="72"></label><label>New password<input name="new_password" type="password" autocomplete="new-password" required minlength="8" maxlength="72"></label><label>Confirm new password<input name="confirm_password" type="password" autocomplete="new-password" required minlength="8" maxlength="72"></label><button class="btn primary">Change password</button></form></section>';
}
function render_activity_visuals(array $a):void{
 $imgs=activity_images($a);$expected=visual_manifest()[(string)$a['id']]??[];
 if(!$imgs){
  if(!empty($expected['external_picture']))echo '<div class="visual-notice" role="note">Use the picture of '.e($expected['external_picture']).' provided by your teacher for this question.</div>';
  elseif(!empty($expected['images']))echo '<div class="visual-notice" role="alert">This activity’s picture has not been set up yet. Please ask your teacher to report activity '.$a['id'].'.</div>';
  return;
 }
 echo '<div class="visual-gallery '.(count($imgs)>1?'multiple':'').'">';
 foreach($imgs as $img){$path=resolved_image_path($img);
  if(!$path){echo '<div class="visual-notice" role="alert">This picture is unavailable. Please tell your teacher: activity '.$a['id'].'.</div>';continue;}
  echo '<figure class="activity-visual"><a href="'.e($path).'" target="_blank" rel="noopener"><img src="'.e($path).'" alt="Module picture for '.e($a['title']).'" loading="eager" data-activity-image="'.$a['id'].'"></a><figcaption class="image-load-error" hidden>This picture could not load. Please tell your teacher: activity '.$a['id'].'.</figcaption></figure>';
 }echo '</div><p class="image-hint">Tap a picture to see it larger.</p>';
}
function visual_audit_view():void{
 require_role('admin');$manifest=visual_manifest();$issues=[];$count=0;$pictures=0;
 foreach(rows('SELECT * FROM activities ORDER BY lesson_id,id') as $a){$count++;$imgs=activity_images($a);$m=$manifest[(string)$a['id']]??[];
  if(!$imgs&&(!empty($m['images'])||!empty($m['external_picture'])))$issues[]=['a'=>$a,'problem'=>!empty($m['external_picture'])?'Upload an approved picture of '.$m['external_picture'].'. The exact composition is not supplied in the PDF.':'No picture assigned. Apply 004_visuals.sql; edited activities must be checked in Lesson Studio.','path'=>null];
  foreach($imgs as $img){$pictures++;$resolved=resolved_image_path($img);if(!$resolved||$resolved!==$img)$issues[]=['a'=>$a,'problem'=>$resolved?'Lesson-folder file missing; original module copy is being used. Upload the complete assets folder.':'File missing or unreadable on this server. Upload it to the assets folder beside public/index.php.','path'=>$img];}
 }
 echo '<div class="pageheading"><div><h1>Activity image check</h1><p>'.$count.' activities checked · '.$pictures.' image references · '.count($issues).' items need attention.</p><p>This checks the database and files on the server running BULIG.</p></div></div>';
 if(!$manifest)echo '<div class="visual-notice">Upload database/visual-manifest.json for the complete assignment check.</div>';
 foreach($issues as $i){$a=$i['a'];echo '<section class="card"><h2>Lesson '.$a['lesson_id'].' · Activity '.$a['id'].' · '.e($a['title']).'</h2><p>'.e($i['problem']).'</p>'.($i['path']?'<p class="preserve">'.e($i['path']).'</p>':'').'<p>'.e($a['prompt']).'</p><a class="btn secondary" href="?page=edit_activity&id='.$a['id'].'">Edit activity pictures</a></section>';}
 echo '<section class="card"><h2>Verify browser loading</h2><p>Open a lesson below to test every assigned picture in your browser. This also detects HTTP errors that a filesystem check cannot detect.</p><nav class="lesson-tabs">';for($n=1;$n<=12;$n++)echo '<a href="?page=visual_audit&lesson='.$n.'">'.$n.'</a>';echo '</nav></section>';
 $lid=(int)($_GET['lesson']??0);if($lid>=1&&$lid<=12){echo '<div class="image-audit-results" role="status">Loading pictures…</div>';foreach(rows('SELECT * FROM activities WHERE lesson_id=? ORDER BY id',[$lid]) as $a){if(!activity_images($a))continue;echo '<section class="card"><h2>Activity '.$a['id'].' · '.e($a['title']).'</h2>';render_activity_visuals($a);echo '</section>';}}
}

function identity_banner(array $u,string $page):void{
 $home=$page==='dashboard';$detail=ucfirst($u['role']);
 if($u['role']==='pupil'){$p=one('SELECT grade_level,section FROM pupils WHERE user_id=?',[$u['id']]);$detail=$p?'Grade '.$p['grade_level'].' · '.$p['section']:'Pupil';}
 elseif($u['role']==='teacher'){$sections=teacher_sections((int)$u['id']);$names=array_map(fn($s)=>'Grade '.$s['grade_level'].' · '.$s['name'],array_slice($sections,0,2));$detail=$names?implode(' / ',$names).(count($sections)>2?' + '.(count($sections)-2).' more':''):'Teacher · Your classroom';}
 else $detail='Administrator · BULIG school workspace';
 echo '<section class="identity-banner '.($home?'identity-home':'identity-compact').'" aria-label="Your profile"><a class="identity-photo" href="?page=profile" aria-label="View or change your profile picture">'.avatar($u).'<span class="photo-edit">'.icon('edit').'</span></a><div class="identity-copy"><span class="eyebrow">'.($home?($u['role']==='pupil'?'WELCOME TO YOUR LITTLE WORLD OF LEARNING':'WELCOME BACK'):'YOUR BULIG SPACE').'</span><'.($home?'h1':'h2').'>'.($home?'Hi, ':'').e($u['name']).($home?'!':'').'</'.($home?'h1':'h2').'><p class="identity-section">'.e($detail).'</p>'.($home&&$u['role']==='pupil'?'<p class="identity-message">Let’s learn something wonderful today.</p>':'').'</div>'.($home&&$u['role']==='pupil'?'<img class="identity-art" src="assets/design/reading-garden.svg" alt="" aria-hidden="true">':'').'</section>';
}
function pupil_progress_cards(int $pid,array $s,?array $assigned):void{
 $level=$assigned?level_label((int)$assigned['id']):'Not assigned';$next=one('SELECT title,required_xp FROM rewards WHERE active=1 AND required_xp>? ORDER BY required_xp,id LIMIT 1',[$s['xp']]);
 echo '<section class="pupil-stats" aria-label="Your learning progress"><div class="pupil-stat level-stat"><span class="stat-label">Starting level</span><strong>'.e(str_replace('Level ','',$level)).'</strong><span class="stat-foot">Chosen by your teacher</span></div><div class="pupil-stat xp-stat"><span class="stat-label">'.icon('bolt').'Your learning XP</span><strong>'.(int)$s['xp'].' <small>XP</small></strong>';
 if($next)echo '<progress value="'.(int)$s['xp'].'" max="'.(int)$next['required_xp'].'" aria-label="XP toward your next reward"></progress><span class="stat-foot">'.(int)$s['xp'].' / '.(int)$next['required_xp'].' XP · '.e($next['title']).'</span>';
 else echo '<span class="stat-foot">Every little effort counts.</span>';
 echo '</div><div class="pupil-stat streak-stat"><span class="stat-label">'.icon('fire').'Learning streak</span><strong>'.(int)$s['current_streak'].' <small>'.((int)$s['current_streak']===1?'day':'days').'</small></strong><span class="stat-foot">Keep your curiosity growing</span></div><a class="pupil-stat badge-stat" href="?page=achievements"><span class="stat-label">'.icon('star').'My badges</span><strong>'.(int)val('SELECT COUNT(*) FROM pupil_badges WHERE pupil_id=?',[$pid]).'</strong><span class="stat-foot">See your achievements '.icon('arrow').'</span></a></section>';
}

function pupil_details_fields(array $p):string{
 $s='<label>Sex<select name="sex" required><option value="">Choose Male or Female</option>';
 foreach(['male'=>'Male','female'=>'Female'] as $key=>$label)$s.='<option value="'.$key.'" '.(($p['sex']??'')===$key?'selected':'').'>'.$label.'</option>';
 return $s.'</select></label><label>LRN (12 digits)<input name="lrn" type="text" inputmode="numeric" pattern="[0-9]{12}" minlength="12" maxlength="12" value="'.e($p['lrn']??'').'" placeholder="Enter learner reference number"><small>Leave blank if the LRN is not available yet. The pupil login ID stays the same.</small></label>';
}
function avatar_picker(array $u):void{
 $choices=profile_avatar_choices();$selected='';foreach($choices as $key=>$v)if(($u['avatar_path']??'')==='assets/avatars/'.$key.'.png')$selected=$key;
 echo '<section class="card avatar-picker"><span class="eyebrow">A LITTLE PICTURE OF YOU</span><h2>Choose your profile picture</h2><p>Pick a character you like, or upload your own photo below.</p><form method="post">'.csrf_field().'<input type="hidden" name="action" value="choose_avatar"><fieldset><legend>Choose one of six characters</legend><div class="avatar-options">';
 foreach($choices as $key=>$v)echo '<label class="avatar-option"><input type="radio" name="avatar_key" value="'.$key.'" '.($selected===$key?'checked':'').' required><span class="avatar-option-picture"><img src="assets/avatars/'.$key.'.png" alt="'.e($v[0]).'" width="120" height="120"><span class="avatar-picked">'.icon('check').'</span></span><span class="avatar-option-label">'.e(explode(' · ',$v[0])[0]).'</span></label>';
 echo '</div></fieldset><button class="btn primary">Use this picture</button></form></section>';
}

function pupil_next_step(int $pid):void{
 $next=next_learning_lesson($pid);
 echo '<section class="next-adventure"><div class="adventure-copy"><span class="adventure-tag">'.icon('book').' YOUR LEARNING ADVENTURE</span><h2>'.($next?'A little practice.<br>A brighter day.':'Every step helps you grow.').'</h2><p>'.($next?'Next up: '.e(level_label((int)$next['level_id']).' · '.$next['subtitle']).'.':'Explore your available levels below. Your teacher can choose your starting level.').'</p>';
 if($next)echo '<a class="btn primary" href="?page=lesson&id='.(int)$next['id'].'">Let’s keep learning '.icon('arrow').'</a><a class="adventure-link" href="?page=dashboard&level='.$next['level_id'].'">See my learning path</a>';
 echo '</div><div class="adventure-art"><img src="assets/design/reading-garden.svg" alt="An open book in a leafy learning garden"><span class="adventure-note">One small step, every day</span></div></section>';
}

function narration_controls(string $text):void{
 echo '<div class="narration" data-text="'.e($text).'"><button type="button" class="btn quiet" data-speech="play">'.icon('sound').'Listen</button><button type="button" class="iconbutton light" data-speech="pause" aria-label="Pause or resume">'.icon('pause').'</button><button type="button" class="iconbutton light" data-speech="replay" aria-label="Replay">'.icon('replay').'</button><button type="button" class="iconbutton light" data-speech="stop" aria-label="Stop">'.icon('stop').'</button><button type="button" class="iconbutton light" data-speech="mute" aria-label="Mute narration" aria-pressed="false">'.icon('mute').'</button><details class="voice-settings"><summary>Voice</summary><select id="voice-select" aria-label="Narration voice"></select><small id="voice-info">Available voices depend on your device.</small></details></div>';
}
