-- BULIG Level 2A and 2B: one recording per card, the module's own lesson goals, and the lesson start screen
-- instead of the app-written "Let's get ready" pages. Safe to import again (MariaDB).
SET NAMES utf8mb4;

ALTER TABLE activity_completion ADD COLUMN IF NOT EXISTS audio_paths TEXT NULL AFTER audio_path;

-- "Let's get ready" pages (text written by the app, not the module). The lesson start screen shows the module's goals and "My turn" example instead.
UPDATE activities SET published=0 WHERE id IN (226,243,247,252,255,258,262,265,268,271,275,279,282,286,290,295,298,303,308,311,314,317) AND type='reference' AND title LIKE 'Let%s get ready' AND lesson_id BETWEEN 13 AND 34;

-- Lesson goals, as written in the module (used by the Lesson plan panel and the Teacher's Guide).
UPDATE lessons SET objectives='Phoneme Pretest: Phoneme Isolation, Phoneme Identification, Phoneme Categorization, Phoneme Blending, Phoneme Segmentation, Phoneme Deletion, Phoneme Addition, Phoneme Substitution.' WHERE id=13 AND module_id=(SELECT id FROM modules WHERE level_id=2 LIMIT 1);
UPDATE lessons SET objectives='Activity 1. Recognizing Individual Sounds within a Word · Beginning/Initial Sound. At the end of the lesson the pupils are expected to: 1. Recognize the beginning/initial sounds within a word. 2. Recognize the middle/medial sounds within a word. 3. Recognize the ending/final sounds within a word.' WHERE id=14 AND module_id=(SELECT id FROM modules WHERE level_id=2 LIMIT 1);
UPDATE lessons SET objectives='Activity 2. Phoneme Isolation · Middle/Medial Sound. At the end of the lesson the pupils are expected to: 1. Recognize the beginning/initial sounds within a word. 2. Recognize the middle/medial sounds within a word. 3. Recognize the ending/final sounds within a word.' WHERE id=15 AND module_id=(SELECT id FROM modules WHERE level_id=2 LIMIT 1);
UPDATE lessons SET objectives='Activity 3. Phoneme Isolation · Ending/Final Sounds Isolation. At the end of the lesson the pupils are expected to: 1. Recognize the beginning/initial sounds within a word. 2. Recognize the middle/medial sounds within a word. 3. Recognize the ending/final sounds within a word.' WHERE id=16 AND module_id=(SELECT id FROM modules WHERE level_id=2 LIMIT 1);
UPDATE lessons SET objectives='Activity 4: Initial Phoneme Identification. At the end of the lesson the pupils are expected to: 1. Identify the phonemes within each word. 2. Recognize the common sound in different words. 3. Identify the beginning, middle and final phoneme in the given name of the picture.' WHERE id=17 AND module_id=(SELECT id FROM modules WHERE level_id=2 LIMIT 1);
UPDATE lessons SET objectives='Activity 5: Medial Phoneme Identification. At the end of the lesson the pupils are expected to: 1. Identify the phonemes within each word. 2. Recognize the common sound in different words. 3. Identify the beginning, middle and final phoneme in the given name of the picture.' WHERE id=18 AND module_id=(SELECT id FROM modules WHERE level_id=2 LIMIT 1);
UPDATE lessons SET objectives='Activity 6: Final Phoneme Identification. At the end of the lesson the pupils are expected to: 1. Identify the phonemes within each word. 2. Recognize the common sound in different words. 3. Identify the beginning, middle and final phoneme in the given name of the picture.' WHERE id=19 AND module_id=(SELECT id FROM modules WHERE level_id=2 LIMIT 1);
UPDATE lessons SET objectives='Activity 7: Initial Phoneme Categorization. At the end of the lesson the pupils are expected to: 1. Identify the words and pictures that have the odd or different initial sounds. 2. Identify the words and pictures that have the odd or different medial sounds. 3. Identify the words and pictures that have the odd or different final sounds.' WHERE id=20 AND module_id=(SELECT id FROM modules WHERE level_id=2 LIMIT 1);
UPDATE lessons SET objectives='Activity 8: Medial Phoneme Categorization. At the end of the lesson the pupils are expected to: 1. Identify the words and pictures that have the odd or different initial sounds. 2. Identify the words and pictures that have the odd or different medial sounds. 3. Identify the words and pictures that have the odd or different final sounds.' WHERE id=21 AND module_id=(SELECT id FROM modules WHERE level_id=2 LIMIT 1);
UPDATE lessons SET objectives='Activity 9: Final Phoneme Categorization. At the end of the lesson the pupils are expected to: 1. Identify the words and pictures that have the odd or different initial sounds. 2. Identify the words and pictures that have the odd or different medial sounds. 3. Identify the words and pictures that have the odd or different final sounds.' WHERE id=22 AND module_id=(SELECT id FROM modules WHERE level_id=2 LIMIT 1);
UPDATE lessons SET objectives='Activity 10: You Put Me Together. Phoneme blending is the ability to hear the individual sounds in a word, put the sounds together, and say the word that is made.' WHERE id=23 AND module_id=(SELECT id FROM modules WHERE level_id=2 LIMIT 1);
UPDATE lessons SET objectives='Activity 11: Beginning Consonant Phoneme Blending. Phoneme blending is the ability to hear the individual sounds in a word, put the sounds together, and say the word that is made.' WHERE id=24 AND module_id=(SELECT id FROM modules WHERE level_id=2 LIMIT 1);
UPDATE lessons SET objectives='Activity 12: Ending Consonant Phoneme Blending. Phoneme blending is the ability to hear the individual sounds in a word, put the sounds together, and say the word that is made.' WHERE id=25 AND module_id=(SELECT id FROM modules WHERE level_id=2 LIMIT 1);
UPDATE lessons SET objectives='Activity 13: Phoneme Segmenting. At the end of the lesson the pupils are expected to: 1. Segment words into individual phonemes (sounds). 2. Recognize the sound/s in the given word. 3. Count the sound in each word.' WHERE id=26 AND module_id=(SELECT id FROM modules WHERE level_id=2 LIMIT 1);
UPDATE lessons SET objectives='Activity 14: Phoneme Segmenting. At the end of the lesson the pupils are expected to: 1. Segment words into individual phonemes (sounds). 2. Recognize the sound/s in the given word. 3. Count the sound in each word.' WHERE id=27 AND module_id=(SELECT id FROM modules WHERE level_id=2 LIMIT 1);
UPDATE lessons SET objectives='Activity 15. Phoneme Deletion · Beginning Sound Deletion. Phoneme Deletion is the ability to identify how a word would sound if one sound were omitted.' WHERE id=28 AND module_id=(SELECT id FROM modules WHERE level_id=2 LIMIT 1);
UPDATE lessons SET objectives='Activity 16. Phoneme Deletion · Ending/Medial Sound Deletion. Phoneme Deletion is the ability to identify how a word would sound if one sound were omitted.' WHERE id=29 AND module_id=(SELECT id FROM modules WHERE level_id=2 LIMIT 1);
UPDATE lessons SET objectives='Activity 17: Adding Phoneme to the Word. At the end of the lesson the pupils are expected to: 1. Add phoneme to a word to form a new word. 2. Create different words by adding phoneme to the given word.' WHERE id=30 AND module_id=(SELECT id FROM modules WHERE level_id=2 LIMIT 1);
UPDATE lessons SET objectives='Activity 18: Adding Phoneme at the Beginning. At the end of the lesson the pupils are expected to: 1. Add phoneme to a word to form a new word. 2. Create different words by adding phoneme to the given word.' WHERE id=31 AND module_id=(SELECT id FROM modules WHERE level_id=2 LIMIT 1);
UPDATE lessons SET objectives='Activity 19: Phoneme Trade and Hunt. At the end of the lesson the pupils are expected to: 1. Change the different letter sound to form a new word. 2. Change consonant phoneme at the beginning in forming new word. 3. Change consonant phoneme at the end of a word to form a new word.' WHERE id=32 AND module_id=(SELECT id FROM modules WHERE level_id=2 LIMIT 1);
UPDATE lessons SET objectives='Activity 20: I Can Change It. At the end of the lesson the pupils are expected to: 1. Change the different letter sound to form a new word. 2. Change consonant phoneme at the beginning in forming new word. 3. Change consonant phoneme at the end of a word to form a new word.' WHERE id=33 AND module_id=(SELECT id FROM modules WHERE level_id=2 LIMIT 1);
UPDATE lessons SET objectives='Phoneme Posttest: Phoneme Identification, Phoneme Categorization, Phoneme Blending, Phoneme Segmentation, Phoneme Addition, Phoneme Substitution.' WHERE id=34 AND module_id=(SELECT id FROM modules WHERE level_id=2 LIMIT 1);

-- Level 2B: the same lesson start screen instead of the app-written pages, and the module's own lesson goals.
UPDATE activities SET published=0 WHERE id IN (329,341,343,345,347,349,351,353,355,357,359,361,364,366,368,370,372,374,376,378,380,382,384,386) AND type='reference' AND lesson_id BETWEEN 35 AND 58;
UPDATE lessons SET objectives='Phonological Awareness Pre-Test: Blending Onsets and Rimes into Words, Segmenting Words into Onsets and Rimes, Segmenting Words into Syllables, Blending Syllables into Words, Sentence Segmentation, Rhymes and Rhyming Songs.' WHERE id=35 AND module_id=(SELECT id FROM modules WHERE level_id=3 LIMIT 1);
UPDATE lessons SET objectives='Activity 1 · Blending Onset and Rime. By the end of this lesson, pupils will be able to: 1. Identify the onset and rime in simple CVC (consonant-vowel-consonant) words. 2. Blend onset and rime orally to form whole words. 3. Produce new words by changing the onset while keeping the rime constant.' WHERE id=36 AND module_id=(SELECT id FROM modules WHERE level_id=3 LIMIT 1);
UPDATE lessons SET objectives='Activity 2 · Blending Onset and Rime. By the end of this lesson, pupils will be able to: 1. Identify the onset and rime in simple CVC (consonant-vowel-consonant) words. 2. Blend onset and rime orally to form whole words. 3. Produce new words by changing the onset while keeping the rime constant.' WHERE id=37 AND module_id=(SELECT id FROM modules WHERE level_id=3 LIMIT 1);
UPDATE lessons SET objectives='Activity 3 · Blending Onset and Rime. By the end of this lesson, pupils will be able to: 1. Identify the onset and rime in simple CVC (consonant-vowel-consonant) words. 2. Blend onset and rime orally to form whole words. 3. Produce new words by changing the onset while keeping the rime constant.' WHERE id=38 AND module_id=(SELECT id FROM modules WHERE level_id=3 LIMIT 1);
UPDATE lessons SET objectives='Activity 4 · Blending Onset and Rime. By the end of this lesson, pupils will be able to: 1. Identify the onset and rime in simple CVC (consonant-vowel-consonant) words. 2. Blend onset and rime orally to form whole words. 3. Produce new words by changing the onset while keeping the rime constant.' WHERE id=39 AND module_id=(SELECT id FROM modules WHERE level_id=3 LIMIT 1);
UPDATE lessons SET objectives='Activity 5 · Segmenting Onsets and Rimes. By the end of this lesson, pupils will be able to: 1. Orally identify the onset and rime of a given single-syllable word represented by a picture. 2. Physically and verbally segment spoken words into onset and rime using hand motions and chants. 3. Produce the rime of a word when given the onset, and vice versa, using picture supports.' WHERE id=40 AND module_id=(SELECT id FROM modules WHERE level_id=3 LIMIT 1);
UPDATE lessons SET objectives='Activity 6 · Segmenting Onsets and Rimes. By the end of this lesson, pupils will be able to: 1. Orally identify the onset and rime of a given single-syllable word represented by a picture. 2. Physically and verbally segment spoken words into onset and rime using hand motions and chants. 3. Produce the rime of a word when given the onset, and vice versa, using picture supports.' WHERE id=41 AND module_id=(SELECT id FROM modules WHERE level_id=3 LIMIT 1);
UPDATE lessons SET objectives='Activity 7 · Segmenting Onsets and Rimes. By the end of this lesson, pupils will be able to: 1. Orally identify the onset and rime of a given single-syllable word represented by a picture. 2. Physically and verbally segment spoken words into onset and rime using hand motions and chants. 3. Produce the rime of a word when given the onset, and vice versa, using picture supports.' WHERE id=42 AND module_id=(SELECT id FROM modules WHERE level_id=3 LIMIT 1);
UPDATE lessons SET objectives='Activity 8 · Segmenting Words into Syllables. By the end of this lesson, pupils will be able to: 1. Orally segment multisyllabic words into syllables by clapping, tapping, or counting. 2. Identify and sort picture cards based on the number of syllables in each word. 3. Write and represent the syllable breakdown of at least five words using visual markers.' WHERE id=43 AND module_id=(SELECT id FROM modules WHERE level_id=3 LIMIT 1);
UPDATE lessons SET objectives='Activity 9 · Segmenting Words into Syllables. By the end of this lesson, pupils will be able to: 1. Orally segment multisyllabic words into syllables by clapping, tapping, or counting. 2. Identify and sort picture cards based on the number of syllables in each word. 3. Write and represent the syllable breakdown of at least five words using visual markers.' WHERE id=44 AND module_id=(SELECT id FROM modules WHERE level_id=3 LIMIT 1);
UPDATE lessons SET objectives='Activity 10 · Segmenting Words into Syllables. By the end of this lesson, pupils will be able to: 1. Orally segment multisyllabic words into syllables by clapping, tapping, or counting. 2. Identify and sort picture cards based on the number of syllables in each word. 3. Write and represent the syllable breakdown of at least five words using visual markers.' WHERE id=45 AND module_id=(SELECT id FROM modules WHERE level_id=3 LIMIT 1);
UPDATE lessons SET objectives='Activity 11 · Blending Syllables into Words. By the end of this lesson, pupils will be able to: 1. Orally blend separately spoken syllables to identify the whole word. 2. Connect blended words to their corresponding pictures through matching activities. 3. Create and illustrate a new word by blending given syllables.' WHERE id=46 AND module_id=(SELECT id FROM modules WHERE level_id=3 LIMIT 1);
UPDATE lessons SET objectives='Activity 12 · Blending Syllables into Words. By the end of this lesson, pupils will be able to: 1. Orally blend separately spoken syllables to identify the whole word. 2. Connect blended words to their corresponding pictures through matching activities. 3. Create and illustrate a new word by blending given syllables.' WHERE id=47 AND module_id=(SELECT id FROM modules WHERE level_id=3 LIMIT 1);
UPDATE lessons SET objectives='Activity 13 · Blending Syllables into Words. By the end of this lesson, pupils will be able to: 1. Orally blend separately spoken syllables to identify the whole word. 2. Connect blended words to their corresponding pictures through matching activities. 3. Create and illustrate a new word by blending given syllables.' WHERE id=48 AND module_id=(SELECT id FROM modules WHERE level_id=3 LIMIT 1);
UPDATE lessons SET objectives='Activity 14 · Blending Syllables into Words. By the end of this lesson, pupils will be able to: 1. Orally blend separately spoken syllables to identify the whole word. 2. Connect blended words to their corresponding pictures through matching activities. 3. Create and illustrate a new word by blending given syllables.' WHERE id=49 AND module_id=(SELECT id FROM modules WHERE level_id=3 LIMIT 1);
UPDATE lessons SET objectives='Activity 15 · Blending Syllables into Words. By the end of this lesson, pupils will be able to: 1. Orally blend separately spoken syllables to identify the whole word. 2. Connect blended words to their corresponding pictures through matching activities. 3. Create and illustrate a new word by blending given syllables.' WHERE id=50 AND module_id=(SELECT id FROM modules WHERE level_id=3 LIMIT 1);
UPDATE lessons SET objectives='Activity 16 · Sentence Segmentation. By the end of this lesson, pupils will be able to: 1. Orally segment a simple spoken sentence into individual words (e.g., "The cat runs." → "The / cat / runs."). 2. Identify and count the number of words in a spoken or written sentence. 3. Represent a sentence visually using counters, blocks, or written boxes, one per word.' WHERE id=51 AND module_id=(SELECT id FROM modules WHERE level_id=3 LIMIT 1);
UPDATE lessons SET objectives='Activity 17 · Sentence Segmentation. By the end of this lesson, pupils will be able to: 1. Orally segment a simple spoken sentence into individual words (e.g., "The cat runs." → "The / cat / runs."). 2. Identify and count the number of words in a spoken or written sentence. 3. Represent a sentence visually using counters, blocks, or written boxes, one per word.' WHERE id=52 AND module_id=(SELECT id FROM modules WHERE level_id=3 LIMIT 1);
UPDATE lessons SET objectives='Activity 18 · Sentence Segmentation. By the end of this lesson, pupils will be able to: 1. Orally segment a simple spoken sentence into individual words (e.g., "The cat runs." → "The / cat / runs."). 2. Identify and count the number of words in a spoken or written sentence. 3. Represent a sentence visually using counters, blocks, or written boxes, one per word.' WHERE id=53 AND module_id=(SELECT id FROM modules WHERE level_id=3 LIMIT 1);
UPDATE lessons SET objectives='Activity 19 · Rhyming and Rhyming Songs. By the end of this lesson, pupils will be able to: 1. Identify rhyming pairs from given picture cues through matching games. 2. Generate at least one rhyming word for a given prompt using word families. 3. Participate in and create new verses for rhyming songs and chants.' WHERE id=54 AND module_id=(SELECT id FROM modules WHERE level_id=3 LIMIT 1);
UPDATE lessons SET objectives='Activity 20 · Rhyming and Rhyming Songs. By the end of this lesson, pupils will be able to: 1. Identify rhyming pairs from given picture cues through matching games. 2. Generate at least one rhyming word for a given prompt using word families. 3. Participate in and create new verses for rhyming songs and chants.' WHERE id=55 AND module_id=(SELECT id FROM modules WHERE level_id=3 LIMIT 1);
UPDATE lessons SET objectives='Activity 21 · Rhyming and Rhyming Songs. By the end of this lesson, pupils will be able to: 1. Identify rhyming pairs from given picture cues through matching games. 2. Generate at least one rhyming word for a given prompt using word families. 3. Participate in and create new verses for rhyming songs and chants.' WHERE id=56 AND module_id=(SELECT id FROM modules WHERE level_id=3 LIMIT 1);
UPDATE lessons SET objectives='Activity 22 · Rhyming and Rhyming Songs. By the end of this lesson, pupils will be able to: 1. Identify rhyming pairs from given picture cues through matching games. 2. Generate at least one rhyming word for a given prompt using word families. 3. Participate in and create new verses for rhyming songs and chants.' WHERE id=57 AND module_id=(SELECT id FROM modules WHERE level_id=3 LIMIT 1);
UPDATE lessons SET objectives='Phonological Awareness Post Test: Segmenting Onsets and Rimes, Segmenting Words into Syllables, Blending Syllables into Words, Sentence Segmentation, Rhyming and Rhyming Words.' WHERE id=58 AND module_id=(SELECT id FROM modules WHERE level_id=3 LIMIT 1);

INSERT IGNORE INTO schema_migrations(version) VALUES('021_level2a_cards');
