-- BULIG Level 6 (Graded Reading Comprehension): the new card screens, and the module's own wording.
-- The cards come from database/level6-cards.json (updated in the same upload). These lines change the copies kept in the
-- database (prompt, narration, questions) so Teacher review and Listen read the same words. Safe to import again (MariaDB).
SET NAMES utf8mb4;

-- Grade 1 "Dessert Time!": the module prints "The, Ben gets a donut."
UPDATE activities a JOIN lessons l ON l.id=a.lesson_id JOIN modules m ON m.id=l.module_id SET a.prompt=REPLACE(a.prompt,'Then, Ben gets a donut.','The, Ben gets a donut.'),a.narration=REPLACE(a.narration,'Then, Ben gets a donut.','The, Ben gets a donut.') WHERE m.level_id=7 AND m.grade_level=1 AND l.position=11210 AND a.position=1;
UPDATE questions x JOIN activities a ON a.id=x.activity_id JOIN lessons l ON l.id=a.lesson_id JOIN modules m ON m.id=l.module_id SET x.content=REPLACE(x.content,'Then, Ben gets a donut.','The, Ben gets a donut.') WHERE m.level_id=7 AND m.grade_level=1 AND l.position=11210 AND a.position=1;
-- Grade 2 "Molly Reads Stories": the module prints "When she has finishes reading".
UPDATE activities a JOIN lessons l ON l.id=a.lesson_id JOIN modules m ON m.id=l.module_id SET a.prompt=REPLACE(a.prompt,'When she has finished reading','When she has finishes reading'),a.narration=REPLACE(a.narration,'When she has finished reading','When she has finishes reading') WHERE m.level_id=7 AND m.grade_level=2 AND l.position=7206 AND a.position=1;
UPDATE questions x JOIN activities a ON a.id=x.activity_id JOIN lessons l ON l.id=a.lesson_id JOIN modules m ON m.id=l.module_id SET x.content=REPLACE(x.content,'When she has finished reading','When she has finishes reading') WHERE m.level_id=7 AND m.grade_level=2 AND l.position=7206 AND a.position=1;
-- Grade 2 Activity 5.3 "In the Barn": the module prints "about of their moms".
UPDATE activities a JOIN lessons l ON l.id=a.lesson_id JOIN modules m ON m.id=l.module_id SET a.prompt=REPLACE(a.prompt,'They told each other about their moms.','They told each other about of their moms.'),a.narration=REPLACE(a.narration,'They told each other about their moms.','They told each other about of their moms.') WHERE m.level_id=7 AND m.grade_level=2 AND l.position=20219 AND a.position=1;
UPDATE questions x JOIN activities a ON a.id=x.activity_id JOIN lessons l ON l.id=a.lesson_id JOIN modules m ON m.id=l.module_id SET x.content=REPLACE(x.content,'They told each other about their moms.','They told each other about of their moms.') WHERE m.level_id=7 AND m.grade_level=2 AND l.position=20219 AND a.position=1;
-- Grade 2 pre-test and post-test items 11-15 (Pearl), as printed in the module.
UPDATE activities a JOIN lessons l ON l.id=a.lesson_id JOIN modules m ON m.id=l.module_id SET a.prompt=REPLACE(a.prompt,'11. They are stories about brave kids.','11. They is stories about brave kids.'),a.narration=REPLACE(a.narration,'11. They are stories about brave kids.','11. They is stories about brave kids.') WHERE m.level_id=7 AND m.grade_level=2 AND l.position=1100 AND a.position=3;
UPDATE questions x JOIN activities a ON a.id=x.activity_id JOIN lessons l ON l.id=a.lesson_id JOIN modules m ON m.id=l.module_id SET x.content=REPLACE(x.content,'11. They are stories about brave kids.','11. They is stories about brave kids.') WHERE m.level_id=7 AND m.grade_level=2 AND l.position=1100 AND a.position=3;
UPDATE activities a JOIN lessons l ON l.id=a.lesson_id JOIN modules m ON m.id=l.module_id SET a.prompt=REPLACE(a.prompt,'14. She is a quiet girl.','14. She is quiet girl.'),a.narration=REPLACE(a.narration,'14. She is a quiet girl.','14. She is quiet girl.') WHERE m.level_id=7 AND m.grade_level=2 AND l.position=1100 AND a.position=3;
UPDATE questions x JOIN activities a ON a.id=x.activity_id JOIN lessons l ON l.id=a.lesson_id JOIN modules m ON m.id=l.module_id SET x.content=REPLACE(x.content,'14. She is a quiet girl.','14. She is quiet girl.') WHERE m.level_id=7 AND m.grade_level=2 AND l.position=1100 AND a.position=3;
UPDATE activities a JOIN lessons l ON l.id=a.lesson_id JOIN modules m ON m.id=l.module_id SET a.prompt=REPLACE(a.prompt,'15. She loved adventure stories.','15. She loved adventures stories.'),a.narration=REPLACE(a.narration,'15. She loved adventure stories.','15. She loved adventures stories.') WHERE m.level_id=7 AND m.grade_level=2 AND l.position=1100 AND a.position=3;
UPDATE questions x JOIN activities a ON a.id=x.activity_id JOIN lessons l ON l.id=a.lesson_id JOIN modules m ON m.id=l.module_id SET x.content=REPLACE(x.content,'15. She loved adventure stories.','15. She loved adventures stories.') WHERE m.level_id=7 AND m.grade_level=2 AND l.position=1100 AND a.position=3;
UPDATE activities a JOIN lessons l ON l.id=a.lesson_id JOIN modules m ON m.id=l.module_id SET a.prompt=REPLACE(a.prompt,'11. They are stories about brave kids.','11. They is stories about brave kids.'),a.narration=REPLACE(a.narration,'11. They are stories about brave kids.','11. They is stories about brave kids.') WHERE m.level_id=7 AND m.grade_level=2 AND l.position=22300 AND a.position=3;
UPDATE questions x JOIN activities a ON a.id=x.activity_id JOIN lessons l ON l.id=a.lesson_id JOIN modules m ON m.id=l.module_id SET x.content=REPLACE(x.content,'11. They are stories about brave kids.','11. They is stories about brave kids.') WHERE m.level_id=7 AND m.grade_level=2 AND l.position=22300 AND a.position=3;
UPDATE activities a JOIN lessons l ON l.id=a.lesson_id JOIN modules m ON m.id=l.module_id SET a.prompt=REPLACE(a.prompt,'14. She is a quiet girl.','14. She is quiet girl.'),a.narration=REPLACE(a.narration,'14. She is a quiet girl.','14. She is quiet girl.') WHERE m.level_id=7 AND m.grade_level=2 AND l.position=22300 AND a.position=3;
UPDATE questions x JOIN activities a ON a.id=x.activity_id JOIN lessons l ON l.id=a.lesson_id JOIN modules m ON m.id=l.module_id SET x.content=REPLACE(x.content,'14. She is a quiet girl.','14. She is quiet girl.') WHERE m.level_id=7 AND m.grade_level=2 AND l.position=22300 AND a.position=3;
UPDATE activities a JOIN lessons l ON l.id=a.lesson_id JOIN modules m ON m.id=l.module_id SET a.prompt=REPLACE(a.prompt,'15. She loved adventure stories.','15. She loved adventures stories.'),a.narration=REPLACE(a.narration,'15. She loved adventure stories.','15. She loved adventures stories.') WHERE m.level_id=7 AND m.grade_level=2 AND l.position=22300 AND a.position=3;
UPDATE questions x JOIN activities a ON a.id=x.activity_id JOIN lessons l ON l.id=a.lesson_id JOIN modules m ON m.id=l.module_id SET x.content=REPLACE(x.content,'15. She loved adventure stories.','15. She loved adventures stories.') WHERE m.level_id=7 AND m.grade_level=2 AND l.position=22300 AND a.position=3;
-- Grade 4 "Raindrops": the module prints "I hear a sign, a thirsty sigh".
UPDATE activities a JOIN lessons l ON l.id=a.lesson_id JOIN modules m ON m.id=l.module_id SET a.prompt=REPLACE(a.prompt,'I hear a sigh, a thirsty sigh','I hear a sign, a thirsty sigh'),a.narration=REPLACE(a.narration,'I hear a sigh, a thirsty sigh','I hear a sign, a thirsty sigh') WHERE m.level_id=7 AND m.grade_level=4 AND l.position=6205 AND a.position=1;
UPDATE questions x JOIN activities a ON a.id=x.activity_id JOIN lessons l ON l.id=a.lesson_id JOIN modules m ON m.id=l.module_id SET x.content=REPLACE(x.content,'I hear a sigh, a thirsty sigh','I hear a sign, a thirsty sigh') WHERE m.level_id=7 AND m.grade_level=4 AND l.position=6205 AND a.position=1;

-- Grade 2 Activity 5.3 "In the Barn" item 3: the module prints "The sound the piglet meow, meow, meow."
UPDATE activities a JOIN lessons l ON l.id=a.lesson_id JOIN modules m ON m.id=l.module_id SET a.prompt=REPLACE(a.prompt,'The sound the piglet makes is meow, meow, meow.','The sound the piglet meow, meow, meow.'),a.narration=REPLACE(a.narration,'The sound the piglet makes is meow, meow, meow.','The sound the piglet meow, meow, meow.') WHERE m.level_id=7 AND m.grade_level=2 AND l.position=20219 AND a.position=1;
UPDATE questions x JOIN activities a ON a.id=x.activity_id JOIN lessons l ON l.id=a.lesson_id JOIN modules m ON m.id=l.module_id SET x.content=REPLACE(x.content,'The sound the piglet makes is meow, meow, meow.','The sound the piglet meow, meow, meow.') WHERE m.level_id=7 AND m.grade_level=2 AND l.position=20219 AND a.position=1;
-- Grade 2 Activity 3.2: the module prints "Luis rides the big train work."
UPDATE activities a JOIN lessons l ON l.id=a.lesson_id JOIN modules m ON m.id=l.module_id SET a.prompt=REPLACE(a.prompt,'Luis rides the big train to work.','Luis rides the big train work.'),a.narration=REPLACE(a.narration,'Luis rides the big train to work.','Luis rides the big train work.') WHERE m.level_id=7 AND m.grade_level=2 AND l.position=11210 AND a.position=1;
UPDATE questions x JOIN activities a ON a.id=x.activity_id JOIN lessons l ON l.id=a.lesson_id JOIN modules m ON m.id=l.module_id SET x.content=REPLACE(x.content,'Luis rides the big train to work.','Luis rides the big train work.') WHERE m.level_id=7 AND m.grade_level=2 AND l.position=11210 AND a.position=1;
-- Grade 2 Activity 5.2 "Reward": the module prints "Ida was a kind-hearted heart girl."
UPDATE activities a JOIN lessons l ON l.id=a.lesson_id JOIN modules m ON m.id=l.module_id SET a.prompt=REPLACE(a.prompt,'Ida was a kind-hearted girl.','Ida was a kind-hearted heart girl.'),a.narration=REPLACE(a.narration,'Ida was a kind-hearted girl.','Ida was a kind-hearted heart girl.') WHERE m.level_id=7 AND m.grade_level=2 AND l.position=19218 AND a.position=1;
UPDATE questions x JOIN activities a ON a.id=x.activity_id JOIN lessons l ON l.id=a.lesson_id JOIN modules m ON m.id=l.module_id SET x.content=REPLACE(x.content,'Ida was a kind-hearted girl.','Ida was a kind-hearted heart girl.') WHERE m.level_id=7 AND m.grade_level=2 AND l.position=19218 AND a.position=1;

INSERT IGNORE INTO schema_migrations(version) VALUES('023_level6_reading');
